## Breast Cancer
python run.py --data_set breast-cancer --project breast-cancer-default --exp_group DLCFormer --dimk_row=128 --dimk_col=8 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask_DLCFormer --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --exp_device cuda:3

## Higgs
python run.py --data_set higgs --project higgs-default --exp_name DLCFormer --dimk_row=128 --dimk_col=8 --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 500000 --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_checkpoint_key higgs__bs_4096__feature_mask_DLCFormer --exp_device cuda:3

## Income
python run.py --data_set income --project income-default --exp_name DLCFormer --dimk_row=128 --dimk_col=16 --data_loader_nprocs=2 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0.0, test=0.0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key income__bs_2048__label_mask_DLCFormer --exp_device cuda:0

## Kick
python run.py --data_set kick --project kick-default --exp_name DLCFormer --dimk_row=128 --dimk_col=4 --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 250000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key kick__bs_4096__feature_mask__label_mask_DLCFormer --exp_device cuda:3

## Forest Cover
python run.py --data_set forest-cover --project forest-cover-default --exp_name DLCFormer --dimk_row=128 --dimk_col=8 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.01 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc True --exp_print_every_nth_forward 1000 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-3 --exp_scheduler polynomial_decay_warmup --exp_num_total_steps 800000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --model_checkpoint_key forest_cover__bs_2048__feature_mask__label_mask_0.5__poly_decay__class_balance_DLCFormer --exp_batch_class_balancing True --exp_device cuda:0

## Boston
python run.py --data_set boston-housing --project boston-housing-default --exp_group DLCFormer --dimk_row=128 --dimk_col=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask_DLCFormer --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --exp_device cuda:3

## Yacht
python run.py --data_set yacht --project yacht-default --exp_group DLCFormer --dimk_row=128 --dimk_col=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep False --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask_DLCFormer --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --exp_device cuda:3